{% set version = "2.2.0" %}
{% set sha256 = "e8169d8b63d00b0cb4d7211f00b29e97b481ffbf6c637967e926d170e8dce856" %}

package:
  name: get_phylomarkers
  version: {{ version }}

build:
  number: 2
  skip: True  # [osx]
  script_env:
   - LC_ALL=POSIX
  run_exports:
    - {{ pin_subpackage('get_phylomarkers', max_pin="x") }}

source:
  url: https://github.com/vinuesa/get_phylomarkers/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:

  build:
    - make
    - perl

  run:
    - bash
    - bc
    - perl
    - r-base 4.3.*
    - r-kdetrees    
    - r-ape
    - r-ggplot2  
    - r-gplots
    - r-vioplot
    - r-plyr
    - r-dplyr  
    - r-stringi
    - r-stringr
    - r-seqinr
    - clustalo
    - snp-sites
    - parallel
    - libxml2
    - newick_utils 

test:
  script_env:
    - LC_ALL=POSIX        
  source_files:
    - CHANGES.txt
    - "*.pl"
    - "*.sh"
    - "*.R"
    - test_get_phylomarkers.t
    - lib
    - bin
    - test_sequences
    - pop_gen_tables

  commands:
    - perl test_get_phylomarkers.t

about:
  home: https://github.com/vinuesa/get_phylomarkers
  summary: "A pipeline to select optimal markers and species tree for microbial/plant phylogenomics"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt

extra:
  identifiers:
    - biotools:get_phylomarkers
    - doi:https://doi.org/10.3389/fmicb.2018.00771
