{% set version = "2.1.1" %}
{% set sha256 = "c17298ad6152eab53ef0254c47d39b500eac4ea431009cfef0d465a7246f0f76" %}

package:
  name: get_phylomarkers
  version: {{ version }}

build:
  number: 0
  noarch: generic
  script_env:
   - LC_ALL=POSIX
  run_exports:
    - {{ pin_subpackage('get_phylomarkers', max_pin="x") }}

source:
  url: https://github.com/vinuesa/get_phylomarkers/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  run:
    - bash
    - wget
    - perl
    - r-base 4.3.*
    - r-kdetrees    
    - r-phangorn
    - r-cluster
    - r-gplots
    - r-vioplot
    - r-plyr
    - r-dplyr  
    - r-stringi
    - r-stringr
    - r-seqinr
    - clustalo
    - fasttree
    - phylip
    - parallel
    - phipack
    - aster
    - iqtree=2.2.0
    - libxml2
    - newick_utils 
    - bc

test:
  script_env:
    - LC_ALL=POSIX        
  source_files:
    - CHANGES.txt
    - "*.pl"
    - "*.sh"
    - "*.R"
    - test_get_phylomarkers.t
    - lib
    - bin
    - test_sequences
    - pop_gen_tables

  commands:
    - perl test_get_phylomarkers.t

about:
  home: https://github.com/vinuesa/get_phylomarkers
  summary: "A pipeline to select optimal markers and species tree for microbial/plant phylogenomics"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt

extra:
  identifiers:
    - biotools:get_phylomarkers
    - doi:https://doi.org/10.3389/fmicb.2018.00771
