{% set version = "2.0.1" %}
{% set sha256 = "ad7067d8c87bf858c7f1d5c82768654aaec3a2c42d19bb30c04e25ba3c6aa869" %}

package:
  name: get_phylomarkers
  version: {{ version }}

build:
  number: 0
  noarch: generic
  script_env:
   - LC_ALL=POSIX
  run_exports:
    - {{ pin_subpackage('get_phylomarkers', max_pin="x") }}

source:
  url: https://github.com/vinuesa/get_phylomarkers/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  run:
    - bash
    - wget
    - perl
    - r-base
    - r-ape
    - r-phangorn
    - r-cluster
    - r-gplots
    - r-vioplot
    - r-plyr
    - r-dplyr  
    - r-ggplot2
    - r-stringi
    - r-stringr
    - r-seqinr
    - r-remotes   
    - clustalo
    - fasttree
    - phylip
    - parallel
    - phipack
    - iqtree
    - newick_utils 
    - bc

test:
  source_files:
    - CHANGES.txt
    - "*.pl"
    - "*.sh"
    - "*.R"
    - lib
    - bin
    - test_sequences
    - pop_gen_tables

  commands:
    - run_get_phylomarkers_pipeline.sh

about:
  home: 
  summary: "A pipeline to select optimal markers for microbial/plant phylogenomics & species tree estimation using the multispecies coalescent and concatenation"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt

extra:
  identifiers:
    - biotools:get_phylomarkers
    - doi:https://doi.org/10.3389/fmicb.2018.00771
